### ISSUE TITLE
Wide character in printf

### ISSUE THREAD

**Issue by SebastianDeiss** [scVENUS/PeekabooAV-amavisd#1]
Amavis has issues with some emails containing probably Unicode characters.

## Expected Behavior
Amavis should process the email without errors.

## Current Behavior
Amavis logs the following error and can't process the mail

```
Error in processing, id=15498-01, parts_decode_ext FAILED: Wide character in printf at (eval 104) line 304. (in reply to end of DATA command))
```

## Steps to Reproduce
Emails to reproduce this issue are available on our test systems.

**Comment by ErdmutPfeifer** [comment]
proposed fix in https://github.com/scVENUS/PeekabooAV-amavisd/commit/5bc22b0485d88826e26e765323447b2b91e3407d

**Comment by SebastianDeiss** [comment]
LGTM. @ErdmutPfeifer: thanks for your help.   
I cherry-picked your commit for our production branches ``master`` and ``debian-find_config_files``.
